import { Translations } from "./types";

export const FOREX_PAIRS = [
  'EUR/USD', 'GBP/USD', 'USD/JPY', 'USD/CHF', 
  'AUD/USD', 'USD/CAD', 'NZD/USD', 'EUR/GBP', 
  'EUR/JPY', 'GBP/JPY', 'XAU/USD'
];

export const STRATEGIES = [
  'Smart Money Concepts (SMC)',
  'Inner Circle Trader (ICT)',
  'Breakout / Retest',
  'Scalping M1',
  'Swing Trading',
  'Support & Resistance'
];

export const APP_NAME = "CNC Trading";

export const TRANSLATIONS: Translations = {
  en: {
    welcome: "Welcome back",
    login_subtitle: "Sign in to save history and access PRO features",
    email: "Email Address",
    phone: "Phone Number",
    password: "Password",
    login_btn: "Login",
    register_link: "Don't have an account? Sign up",
    register_btn: "Create Account",
    dashboard: "Dashboard",
    history: "History",
    settings: "Settings",
    upgrade: "Upgrade to VIP",
    logout: "Logout",
    login_menu: "Login",
    analyze_btn: "Analyze Market",
    signal_strength: "Signal Strength",
    backtest: "Backtesting",
    run_backtest: "Run simulation",
    strategy: "Strategy",
    date_range: "Historical Range",
    net_profit: "Net Profit",
    max_drawdown: "Max Drawdown",
    win_rate: "Win Rate",
    equity_curve: "Equity Curve",
    analyzing: "Analyzing market data...",
    language: "Language",
    theme: "Appearance",
    chart_settings: "Chart Settings",
    trading_pref: "Trading Preferences",
    security: "Security",
    risk_calculator: "Risk Calculator",
    tour_welcome_title: "Welcome to CNC Trading!",
    tour_welcome_desc: "Let's take a quick tour of how to use our professional AI analysis tool."
  },
  pt: {
    welcome: "Bem-vindo de volta",
    login_subtitle: "Entre para guardar histórico e aceder a funções PRO",
    email: "Endereço de Email",
    phone: "Telemóvel",
    password: "Palavra-passe",
    login_btn: "Entrar",
    register_link: "Não tem conta? Registe-se",
    register_btn: "Criar Conta",
    dashboard: "Dashboard",
    history: "Histórico",
    settings: "Definições",
    upgrade: "Mudar para VIP",
    logout: "Sair",
    login_menu: "Entrar",
    analyze_btn: "Analisar Mercado",
    signal_strength: "Força do Sinal",
    backtest: "Backtesting",
    run_backtest: "Iniciar simulação",
    strategy: "Estratégia",
    date_range: "Intervalo Histórico",
    net_profit: "Lucro Líquido",
    max_drawdown: "Rebaixamento Máx.",
    win_rate: "Taxa de Acerto",
    equity_curve: "Curva de Capital",
    analyzing: "A analisar dados de mercado...",
    language: "Idioma",
    theme: "Aparência",
    chart_settings: "Configuração do Gráfico",
    trading_pref: "Preferências de Trading",
    security: "Segurança",
    risk_calculator: "Calculadora de Risco",
    tour_welcome_title: "Bem-vindo ao CNC Trading!",
    tour_welcome_desc: "Vamos fazer um tour rápido de como usar nossa ferramenta de análise de IA profissional."
  },
  fr: {
    welcome: "Bon retour",
    login_subtitle: "Connectez-vous pour sauvegarder l'historique",
    email: "Adresse Email",
    phone: "Numéro de téléphone",
    password: "Mot de passe",
    login_btn: "Se connecter",
    register_link: "Pas de compte ? Inscrivez-vous",
    register_btn: "Créer un compte",
    dashboard: "Tableau de bord",
    history: "Historique",
    settings: "Paramètres",
    upgrade: "Passer VIP",
    logout: "Déconnexion",
    login_menu: "Connexion",
    analyze_btn: "Analyser le marché",
    signal_strength: "Force du signal",
    backtest: "Backtesting",
    run_backtest: "Lancer la simulation",
    strategy: "Stratégie",
    date_range: "Période historique",
    net_profit: "Profit net",
    max_drawdown: "Drawdown Max",
    win_rate: "Taux de réussite",
    equity_curve: "Courbe de capital",
    analyzing: "Analyse des données...",
    language: "Langue",
    theme: "Apparence",
    chart_settings: "Paramètres du graphique",
    trading_pref: "Préférences de trading",
    security: "Sécurité",
    risk_calculator: "Calculateur de Risque",
    tour_welcome_title: "Bienvenue sur CNC Trading!",
    tour_welcome_desc: "Faisons un tour rapide de l'utilisation de notre outil d'analyse IA professionnel."
  },
  es: {
    welcome: "Bienvenido de nuevo",
    login_subtitle: "Inicia sesión para guardar tu historial y acceder a funciones PRO",
    email: "Correo Electrónico",
    phone: "Teléfono",
    password: "Contraseña",
    login_btn: "Entrar",
    register_link: "¿No tienes cuenta? Regístrate",
    register_btn: "Crear Cuenta",
    dashboard: "Panel de Control",
    history: "Historial",
    settings: "Ajustes",
    upgrade: "Mejorar a VIP",
    logout: "Cerrar Sesión",
    login_menu: "Entrar",
    analyze_btn: "Analizar Mercado",
    signal_strength: "Señal de fuerza",
    backtest: "Backtesting",
    run_backtest: "Iniciar simulación",
    strategy: "Estrategia",
    date_range: "Rango Histórico",
    net_profit: "Beneficio Neto",
    max_drawdown: "Drawdown Máx.",
    win_rate: "Tasa de Acierto",
    equity_curve: "Curva de Capital",
    analyzing: "Analizando datos del mercado...",
    language: "Idioma",
    theme: "Apariencia",
    chart_settings: "Ajustes del Gráfico",
    trading_pref: "Preferências de Trading",
    security: "Seguridad",
    risk_calculator: "Calculadora de Riesgo",
    tour_welcome_title: "¡Bienvenido a CNC Trading!",
    tour_welcome_desc: "Hagamos un tour rápido sobre cómo usar nuestra herramienta profesional de análisis con IA."
  }
};